# Generated by Django 3.0 on 2019-04-12 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='视频标签')),
                ('number', models.IntegerField(default=0, verbose_name='标签数量')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
        migrations.AddField(
            model_name='comment',
            name='num',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='video',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image_url',
            field=models.CharField(max_length=200, verbose_name='封面地址'),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro',
            field=models.TextField(verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='video',
            name='message',
            field=models.TextField(verbose_name='相关信息'),
        ),
        migrations.AlterField(
            model_name='video',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=50, verbose_name='视频名称'),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='video',
            name='tag',
            field=models.ManyToManyField(to='video.Tag', verbose_name='标签'),
        ),
    ]
