# Generated by Django 3.0 on 2019-04-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190412_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='num',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='封面地址'),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro',
            field=models.TextField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='video',
            name='message',
            field=models.TextField(blank=True, verbose_name='相关信息'),
        ),
        migrations.AlterField(
            model_name='video',
            name='photo_url',
            field=models.TextField(blank=True, verbose_name='剧照'),
        ),
        migrations.AlterField(
            model_name='video',
            name='play_url',
            field=models.TextField(blank=True, verbose_name='下载链接'),
        ),
    ]
